on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
permissions:
  # Goreadme needs permissions to update pull requests comments and change contents.
  pull-requests: write
  contents: write
name: Build
jobs:
    test:
        strategy:
            matrix:
                go-version: [ 1.16.x, 1.15.x, 1.14.x, 1.13.x ]
                platform: [ ubuntu-latest, macos-latest, windows-latest ]
        runs-on: ${{ matrix.platform }}
        steps:
            -   name: Install Go
                if: success()
                uses: actions/setup-go@v1
                with:
                    go-version: ${{ matrix.go-version }}
            -   name: Checkout code
                uses: actions/checkout@v1
            -   name: Run tests
                run: go test -v -race ./...

    analyze:
        name: Analyze
        runs-on: ubuntu-latest     
        permissions:
            actions: read
            contents: read
            security-events: write
        steps:
        - name: Checkout repository
          uses: actions/checkout@v2
        - name: Initialize CodeQL
          uses: github/codeql-action/init@v1
          with:
            languages: go
        - name: Autobuild
          uses: github/codeql-action/autobuild@v1
        - name: Perform CodeQL Analysis
          uses: github/codeql-action/analyze@v1

    codecov:
        runs-on: ubuntu-latest
        needs: [ test, analyze ]
        steps:
            -   name: Install Go
                if: success()
                uses: actions/setup-go@v1
                with:
                    go-version: 1.16.x
            -   name: Checkout code
                uses: actions/checkout@v1
            -   name: Run tests
                run: go mod tidy && go test -v -race -covermode=atomic -coverprofile=coverage.out ./...
            -   name: CodeCov
                uses: codecov/codecov-action@v2

    lint:
        name: Lint project using GolangCI Lint
        runs-on: ubuntu-latest
        needs: [ test, analyze ]
        steps:
            -   name: Check out code into the Go module directory
                uses: actions/checkout@v1
            -   name: GolangCI-Lint Action
                uses: golangci/golangci-lint-action@v2.5.2
                with:
                    version: latest
                    only-new-issues: true
                    args: --issues-exit-code=0

    goreadme:
        runs-on: ubuntu-latest
        needs: [codecov, lint]
        steps:
        - name: Check out repository
          uses: actions/checkout@v2
        - name: Update readme according to Go doc
          uses: posener/goreadme@v1
          with:
            badge-codecov: 'true'
            badge-godoc: 'true'
            email: 'justin@dynam.ac'
            title: 'Go-LogAdapter'
            # Optional: Token allows goreadme to comment the PR with diff preview.
            github-token: '${{ secrets.GITHUB_TOKEN }}'
            
    release:
        #if: startsWith(github.ref, 'refs/tags/')
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        needs: [goreadme]
        runs-on: ubuntu-latest
        steps:
        - name: Check out repository
          uses: actions/checkout@v2
        - uses: release-drafter/release-drafter@master
          with: 
            prerelease: ${{ contains(github.ref, '-rc') || contains(github.ref, '-b') || contains(github.ref, '-a') }}
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
